manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: siddhantac #new entry
      url-base: https://github.com/siddhantac #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view #new entry
      remote: siddhantac #new entry
      revision: slower-animation #new entry
  self:
    path: config
